spring.application.name=api-gateway
server.port=8080


spring.cloud.gateway.routes[0].id=document-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/documents/**

spring.cloud.gateway.routes[1].id=analysis-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/analysis/**

